version: '3.4'
services:
  db:
    image: fernandooliveira19/mysql-traveler-service
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: F_mo2369
      MYSQL_PASSWORD: F_mo2369
      MYSQL_DATABASE: traveler-service-db
    ports:
      - "3308:3306"
    networks:
      - fr2g-network
  traveler-service:
    image: fernandooliveira19/traveler-service 
    restart: always
    build: ./traveler-service
    working_dir: /traveler-service
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: dev
    volumes:
      - ./traveler-service:/traveler-service
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - fr2g-network    
networks:
    fr2g-network:
        driver: bridge
    